server.modules = (
    "mod_access",
    "mod_alias",
    "mod_deflate",
    "mod_redirect",
    "mod_rewrite"
)

server.document-root        = "/var/www/html"
server.port                 = 8000
server.username             = "lighttpd"
server.groupname            = "lighttpd"

index-file.names            = ( "index.html" )
url.access-deny             = ( "~", ".inc" )
static-file.exclude-extensions = ( ".php", ".pl", ".fcgi" )

# Configuración de compresión
deflate.allowed-encodings = ( "gzip", "deflate" )
deflate.cache-dir         = "/var/cache/lighttpd/compress/"
deflate.mimetypes         = (
    "text/html", "text/plain", "text/css", "text/javascript",
    "application/javascript", "application/json", "image/svg+xml"
)

mimetype.assign = (
  ".html" => "text/html",
  ".txt"  => "text/plain",
  ".css"  => "text/css",
  ".js"   => "application/javascript",
  ".json" => "application/json",
  ".webp" => "image/webp",
  ".svg"  => "image/svg+xml",
  ".ico"  => "image/x-icon"
)

# REGLAS PARA ASTRO (Clean URLs)
url.rewrite-if-not-file = (
    "^/([^.]+)$" => "/$1/index.html"
)
